apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpg01-poi-map-app-dev
  annotations:
    argocd/app-name: hpg01-poi-map-app-dev
    backstage.io/kubernetes-id: hpg01-poi-map-app
    backstage.io/kubernetes-namespace: hpg01
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-2024/hpg01-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/dev-pipelines/ns/hpg01/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/k8s/ns/hpg01/deployments/hpg01-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/#https://github.com/rhdh-2024/hpg01-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hpg01-poi-map-app-hpg01.apps.rosa-qxs8d.dusy.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:hpgrahsl"
  system: workshop-system-hpg01
  consumesApis:
    - gateway-api-hpg01
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hpg01
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:hpgrahsl"
